version: 1
formatters:
    simple:
        style: $
        format: '$levelname - $filename($lineno): $message'
    complex:
        style: $
        format: '$levelname | $filename:$funcName($lineno) > $message'
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    fileh:
        class: logging.FileHandler
        level: DEBUG
        formatter: complex
        filename: GnucashLog
        filters: [special]
        delay: yes
    file_monarch_ui:
        class: logging.FileHandler
        level: DEBUG
        formatter: complex
        filename: GncTxsFromMonarch
        filters: [special]
        delay: yes
    file_monarch_copy:
        class: logging.FileHandler
        level: DEBUG
        formatter: complex
        filename: CopyMonarchLog
        filters: [special]
        delay: yes
    file_google_budget_ui:
        class: logging.FileHandler
        level: DEBUG
        formatter: complex
        filename: UpdateGoogleSheet
        filters: [special]
        delay: yes
    file_revexp_update:
        class: logging.FileHandler
        level: DEBUG
        formatter: complex
        filename: RevExpLog
        filters: [special]
        delay: yes
    file_balance_update:
        class: logging.FileHandler
        level: DEBUG
        formatter: complex
        filename: BalanceLog
        filters: [special]
        delay: yes
    file_assets_update:
        class: logging.FileHandler
        level: DEBUG
        formatter: complex
        filename: AssetsLog
        filters: [special]
        delay: yes
filters:
    special:
        (): mhsLogging.SpecialFilter
loggers:
    basic:
        level: DEBUG
        handlers: [console,fileh]
        propagate: no
    MonarchGnucashServices:
        level: DEBUG
        handlers: [console,file_monarch_ui]
        propagate: no
    parseMonarchCopyRep:
        level: DEBUG
        handlers: [console,file_monarch_copy]
        propagate: no
    UpdateBudgetUI:
        level: DEBUG
        handlers: [console,file_google_budget_ui]
        propagate: no
    updateRevExps:
        level: DEBUG
        handlers: [console,file_revexp_update]
        propagate: no
    updateBalance:
        level: DEBUG
        handlers: [console,file_balance_update]
        propagate: no
    updateAssets:
        level: DEBUG
        handlers: [console,file_assets_update]
        propagate: no
root:
    level: INFO
    handlers: [console]
