version: 1
formatters:
    simple:
        style: $
        format: '$levelname - $filename($lineno): $message'
    complex:
        style: $
        format: '$levelname[$asctime] / $filename:$funcName($lineno) > $message'
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    fileh:
        class: logging.FileHandler
        level: DEBUG
        formatter: complex
        filename: GnucashLog
        filters: [special]
filters:
    special:
        (): python_utilities.SpecialFilter
loggers:
    gnucash:
        level: DEBUG
        handlers: [console,fileh]
        propagate: no
root:
    level: INFO
    handlers: [console]
